server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=UTC&useSSL=false
    username: root
    password: Snow103082..
    hikari:
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: HikariConnectionPool
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟)
      max-lifetime: 1800000 #控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 5000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml